# Table of Content


1. **[Creating Modules]**
<br><br> 
2. **[Importing Modules (Pandas)]**
<br><br> 
2. **[Pandas DataFrame]**
<br><br>
3. **[Manipulating DataFrame]**

<a id="pandas"> </a>
# 1. Creating a Module

A module/library in python is simply a way to organize the code, and it contains either python classes or just functions.

### Quick look at functions

In [104]:
# what are functions and arguments
def add(x,y):
    c = x+y
    return c

### First let's learn how modules work

In [105]:
# create this math_operations.py file in your computer at same location as this file

def add_numbers(a, b):
    """Add two numbers."""
    return a + b

def subtract_numbers(a, b):
    """Subtract two numbers."""
    return a - b

def multiply_numbers(a=1, b=1):
    """Multiply two numbers with default arguments."""
    return a * b

In [ ]:
import math_operations
print(math_operations.__file__)

In [107]:
# import entire module
import math_operations
result = math_operations.add_numbers(2,3)

In [ ]:
# import a specific function
from math_operations import subtract_numbers
result = subtract_numbers(10, 5)

In [108]:
# import with alias
import math_operations as mo
mo.add_numbers(2,3)

5

In [ ]:
# Let's check where we have all our modules stored
import sys
print(sys.path)

<a id="pandas"> </a>
# 2. Pandas

<table align="left">
    <tr>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b> Pandas contain data structures and data manipulation tools designed for data cleaning and analysis.
<br><br>
                       Pandas is designed for working with tabular data.<br><br>

**How to install and import pandas?**<br>
1. Install pandas:<br><br>
`!pip install pandas`<br><br>
2. Import pandas:<br><br>
`import pandas as pd`

In [ ]:
# install pandas (one time only)
#!pip install pandas

In [2]:
#import pandas 
import pandas as pd

 `as` is used as an alias in pandas. So from now on we will use `pd.` instead of `pandas.` 
 
<br>
<span style="color:crimson">Always use libraries if they are freely available. It saves time, and those codes are already tested, debugged and optimized.</span>

<a id="dataframes"> </a>
# 2. Pandas DataFrames

<table align="left">
    <tr>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b> A DataFrame is a tabular representation of data containing an ordered collection of columns, each of which can be a different type (numeric, string, boolean, and so on). <br><br>                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

## <span style="color:darkgreen;">To read data from a csv file</span>

In [3]:
# read the example.csv file in a dataframe
data = pd.read_csv('BMI.csv')

In [3]:
# check the type
type(data)

pandas.core.frame.DataFrame

On checking the data type, we notice it is read as pandas data frame.

## <span style="color:darkgreen;">To print top & bottom rows of the data</span>

In [4]:
#top 3 rows (head)
data.head(3)

   Age  Weight (in kg)  Height (in m)
0   45              60           1.35
1   12              43           1.21
2   54              78           1.50

By default, the `.head()` will display **first** five rows. However, we can set the desired number of rows to be displayed.

In [113]:
#bottom 3 rows (tail)
data.tail(5)

    Age  Weight (in kg)  Height (in m)
18   67              78           1.85
19   26              65           1.21
20   68              50           1.32
21   56              76           1.69
22   67              78           1.85

By default, the `.tail()` will display **last** five rows. However, we can set the desired number of rows to be displayed.

## <span style="color:darkgreen;">To obtain the dimensions of the data</span>

In [114]:
# get the shape of the dataset
data.shape

(23, 3)

## <span style="color:darkgreen;">To know the data types of a data frame</span>

In [115]:
# get all the data types
data.dtypes

Age                 int64
Weight (in kg)      int64
Height (in m)     float64
dtype: object

We see the data type of each variable.

## <span style="color:darkgreen;">Print more information about the data</span>

In [116]:
# All information together info()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             23 non-null     int64
 1   Weight (in kg)  23 non-null     int64
 2   Height (in m)   23 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 684.0 bytes

We see this output gives the number of rows present in the data `RangeIndex: 23 entries, 0 to 22` There are 23 rows numbered from 0 to 22. And there are a total of three columns - `Data columns (total 3 columns)`. 

Consider `Age 23 non-null int64` indicates that the column named 'Age' has 23 non-null observations having the data type 'int64'

And finally the memory used to save this dataframe is 680 bytes.

In [117]:
# describe() your data
data.describe()

             Age  Weight (in kg)  Height (in m)
count  23.000000       23.000000      23.000000
mean   44.521739       58.304348       1.528261
std    20.586557       19.401112       0.227309
min    10.000000       21.000000       1.210000
25%    26.000000       44.000000       1.320000
50%    54.000000       65.000000       1.520000
75%    62.000000       76.000000       1.690000
max    75.000000       89.000000       1.850000

# `.loc` and `.iloc` methods

## <span style="color:darkgreen;">Indexing a dataframe using `.loc`</span>

`DataFrame.loc[]` is label-based method, which means that you have to specify rows and columns based on their row and column labels.

In [122]:
#syntax
#dataframe.loc[row-start:row-end, column-start:column-end]
#data.loc[:,]
#data.loc[:,'Age']
#data.loc[1,]
data.loc[2:6,]

   Age  Weight (in kg)  Height (in m)
2   54              78           1.50
3   26              65           1.21
4   68              50           1.32
5   21              43           1.52
6   10              32           1.65

In [123]:
# get first row with all columns
data.loc[0,]

Age               45.00
Weight (in kg)    60.00
Height (in m)      1.35
Name: 0, dtype: float64

In [124]:
# get the value of Age in the 1st row
data.loc[0,'Age']

np.int64(45)

## <span style="color:darkgreen;">Selecting multiple rows</span>

In [125]:
# select row 4, 7, 10
data.loc[[4,7,10]]

    Age  Weight (in kg)  Height (in m)
4    68              50           1.32
7    57              34           1.61
10   23              53           1.50

We use two square brackets since we are passing a list of row numbers to be accessed.

## <span style="color:darkgreen;">Selecting a range of rows</span>

In [127]:
# select rows from 11 to 18
data.loc[11:18:3]

    Age  Weight (in kg)  Height (in m)
11   34              65           1.76
14   56              76           1.69
17   56              74           1.69

## <span style="color:darkgreen;">Selecting the first column</span>

In [141]:
# select 1st column with all rows
data.loc[:,['Age']]

    Age
0    45
1    12
2    54
3    26
4    68
5    21
6    10
7    57
8    75
9    32
10   23
11   34
12   55
13   23
14   56
15   67
16   26
17   56
18   67
19   26
20   68
21   56
22   67

## <span style="color:darkgreen;">Select the first two columns</span>

In [139]:
# select the first two columns with all rows
data.loc[:,['Age', 'Weight (in kg)']]

    Age  Weight (in kg)
0    45              60
1    12              43
2    54              78
3    26              65
4    68              50
5    21              43
6    10              32
7    57              34
8    75              23
9    32              21
10   23              53
11   34              65
12   55              89
13   23              45
14   56              76
15   67              78
16   26              65
17   56              74
18   67              78
19   26              65
20   68              50
21   56              76
22   67              78

## <span style="color:darkgreen;">Indexing a dataframe using `.iloc`</span>

`DataFrame.iloc[]` is integer position-based, so you have to specify rows and columns by their integer position values (0-based integer position).

**Note:** the row names are numbers

In [137]:
# using iloc select 'Age' & 'Weight (in kg)'
data.iloc[:,0:2]

    Age  Weight (in kg)
0    45              60
1    12              43
2    54              78
3    26              65
4    68              50
5    21              43
6    10              32
7    57              34
8    75              23
9    32              21
10   23              53
11   34              65
12   55              89
13   23              45
14   56              76
15   67              78
16   26              65
17   56              74
18   67              78
19   26              65
20   68              50
21   56              76
22   67              78

<a id="manipulatingDF"> </a>
# 3. Manipulating a Dataframe

<table align="left">
    <tr>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b> CAUTION:<br>
                        1. DataFrame[column] works for any column name, but DataFrame.column only works when the column name is a valid Python variable name.<br>
                        2. New columns cannot be created with the ` data.BMI ` syntax.
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

## <span style="color:darkgreen;">Adding a new column to the dataframe</span>

In [128]:
# create a new column Gender with a constant value 'Male'
data['Gender'] = 'Male'

In [129]:
# change the value of 4th 7th 10th and 18th instance to 'Female'
data.loc[[4,7,10,18],'Gender'] ='Female'

columns/variables/features mean the same

In [130]:
# create a new column BMI which is given by weight / H**2
data['BMI'] = data['Weight (in kg)'] / data['Height (in m)'] ** 2

In [131]:
# check the shape of the data
data.shape

(23, 5)

People with Age greater than 30

In [132]:
#People with Age greater than 30
data[data['Age'] > 30]

    Age  Weight (in kg)  Height (in m)  Gender        BMI
0    45              60           1.35    Male  32.921811
2    54              78           1.50    Male  34.666667
4    68              50           1.32  Female  28.696051
7    57              34           1.61  Female  13.116778
8    75              23           1.24    Male  14.958377
9    32              21           1.52    Male   9.089335
11   34              65           1.76    Male  20.983988
12   55              89           1.65    Male  32.690542
14   56              76           1.69    Male  26.609713
15   67              78           1.85    Male  22.790358
17   56              74           1.69    Male  25.909457
18   67              78           1.85  Female  22.790358
20   68              50           1.32    Male  28.696051
21   56              76           1.69    Male  26.609713
22   67              78           1.85    Male  22.790358

In [133]:
#How many People with Age greater than 30
data[data['Age'] > 30].count()

Age               15
Weight (in kg)    15
Height (in m)     15
Gender            15
BMI               15
dtype: int64

In [7]:
data['Age'].count()

23

Working with DATAFRAMES

In [ ]:
import pandas as pd
df = pd.DataFrame({'Snumber': [0, 1, 1, 19, 20, 2, 0, 1, 1]})
d = df['Snumber']
ax=d.plot(kind='bar')

# Draw the horizontal line at mean / median
#ax.axhline(y=d.mean(), color='green', linestyle='--', linewidth=2, label=f'Y ={'mean'}')
#ax.axhline(y=d.std(), color='gray', linestyle='-', linewidth=2, label=f'Y = {'std'}')